name = "MyRegistry"
uuid = "273435b0-b57a-4e42-8383-e741f6b3483b"
repo = "https://github.com/janckerchen/jl-local-registry.git"
description = "本地私有注册表"

[packages]
075372ef-9491-42ef-b96d-735a065e5a57 = { name = "KnitUserIO", path = "K/KnitUserIO" }
0c0cabac-adea-46a4-b989-85ad082cde13 = { name = "CloudProvisionVultr", path = "C/CloudProvisionVultr" }
12345678-1234-5678-9abc-123456789abc = { name = "AnsibleOrchestrator", path = "A/AnsibleOrchestrator" }
15a0a7c1-9881-4918-a92f-5ea6b2555332 = { name = "CloudInit", path = "C/CloudInit" }
18d7db35-796d-44e1-8386-4b2a063f0dc3 = { name = "ZeroCore", path = "Z/ZeroCore" }
2309e8d9-e6b5-456d-9051-bf7f574e8534 = { name = "CloudNetworking", path = "C/CloudNetworking" }
240cef0a-9318-4761-93e2-d9e16eccb069 = { name = "KnitHttp", path = "K/KnitHttp" }
250039e9-ffb4-4cc8-99a9-6fd599fdda1e = { name = "VultrCloud", path = "V/VultrCloud" }
2e1b12dd-12a8-4702-adcc-0a56fdfcdc4b = { name = "SSHConfig", path = "S/SSHConfig" }
3f8fd914-8333-4068-8a7e-a1bb52a1c891 = { name = "KnitIntent", path = "K/KnitIntent" }
4b1db1d4-1d7f-4782-9535-0753adab9f85 = { name = "ZeroWizard", path = "Z/ZeroWizard" }
4f10d341-401f-4f02-9507-79d9b1f51bf6 = { name = "CloudUI", path = "C/CloudUI" }
58888f4e-6b76-4670-9d04-eda9c0ce1c3a = { name = "KnitShell", path = "K/KnitShell" }
594c028c-9b1f-409a-8860-915ae3563380 = { name = "CloudVultr", path = "C/CloudVultr" }
66c3412d-2a13-47c6-8507-f9a6b065dcc0 = { name = "KnitCommand", path = "K/KnitCommand" }
71d211c4-67af-4226-bf57-c04ce0a47fa7 = { name = "REPLBuilder", path = "R/REPLBuilder" }
744aca3e-52d2-455a-8de1-c81b4fa033f7 = { name = "CloudProvision", path = "C/CloudProvision" }
7568ab37-29fa-429f-9993-a40ff907fe74 = { name = "KnitCore", path = "K/KnitCore" }
8880a6f3-ad0b-4cd1-b54c-bd72e2e73c43 = { name = "KnitConfig", path = "K/KnitConfig" }
91507d90-1c9e-438c-96c4-1ba597712810 = { name = "KnitState", path = "K/KnitState" }
99523da8-7d47-47b1-81dd-04d3b12d7c54 = { name = "KnitFS", path = "K/KnitFS" }
a2bf8f19-0d18-4b4f-beab-d2df36dc25e4 = { name = "CompositeConfigLoader", path = "C/CompositeConfigLoader" }
ac4f51f7-48c2-4af3-adf1-f52a396a500e = { name = "KnitDI", path = "K/KnitDI" }
af517f51-8746-4ff3-bf07-7ab607636cde = { name = "AnsibleRunner", path = "A/AnsibleRunner" }
b080db75-af2b-41b8-a5e3-f52cafd13da9 = { name = "AbstractCloud", path = "A/AbstractCloud" }
c7ffd6e2-e1c8-49fd-970e-c347847bfaf0 = { name = "KnitCLI", path = "K/KnitCLI" }
e5cf7934-71a6-4e68-8918-299e86b24ce2 = { name = "CloudOrchestrator", path = "C/CloudOrchestrator" }
eedf712c-e094-4e2f-b26f-1b21bbf083bb = { name = "CloudCore", path = "C/CloudCore" }
fa25229b-0c51-49da-a28f-84a77d707b8e = { name = "ZeroCLI", path = "Z/ZeroCLI" }
