name = "MyRegistry"
uuid = "273435b0-b57a-4e42-8383-e741f6b3483b"
repo = "https://github.com/janckerchen/jl-local-registry.git"
description = "本地私有注册表"

[packages]
075372ef-9491-42ef-b96d-735a065e5a57 = { name = "KnitUserIO", path = "K/KnitUserIO" }
240cef0a-9318-4761-93e2-d9e16eccb069 = { name = "KnitHttp", path = "K/KnitHttp" }
3f8fd914-8333-4068-8a7e-a1bb52a1c891 = { name = "KnitIntent", path = "K/KnitIntent" }
58888f4e-6b76-4670-9d04-eda9c0ce1c3a = { name = "KnitShell", path = "K/KnitShell" }
71d211c4-67af-4226-bf57-c04ce0a47fa7 = { name = "REPLBuilder", path = "R/REPLBuilder" }
7568ab37-29fa-429f-9993-a40ff907fe74 = { name = "KnitCore", path = "K/KnitCore" }
8880a6f3-ad0b-4cd1-b54c-bd72e2e73c43 = { name = "KnitConfig", path = "K/KnitConfig" }
91507d90-1c9e-438c-96c4-1ba597712810 = { name = "KnitState", path = "K/KnitState" }
99523da8-7d47-47b1-81dd-04d3b12d7c54 = { name = "KnitFS", path = "K/KnitFS" }
a2bf8f19-0d18-4b4f-beab-d2df36dc25e4 = { name = "CompositeConfigLoader", path = "C/CompositeConfigLoader" }
ac4f51f7-48c2-4af3-adf1-f52a396a500e = { name = "KnitDI", path = "K/KnitDI" }
c7ffd6e2-e1c8-49fd-970e-c347847bfaf0 = { name = "KnitCLI", path = "K/KnitCLI" }
