name = "MyRegistry"
uuid = "273435b0-b57a-4e42-8383-e741f6b3483b"
repo = "https://github.com/janckerchen/jl-local-registry.git"
description = "本地私有注册表"

[packages]
71d211c4-67af-4226-bf57-c04ce0a47fa7 = { name = "REPLBuilder", path = "R/REPLBuilder" }
ac4f51f7-48c2-4af3-adf1-f52a396a500e = { name = "KnitDI", path = "K/KnitDI" }
