name = "MyRegistry"
uuid = "273435b0-b57a-4e42-8383-e741f6b3483b"
repo = "https://github.com/janckerchen/jl-local-registry.git"
description = "本地私有注册表"

[packages]
240cef0a-9318-4761-93e2-d9e16eccb069 = { name = "KnitHttp", path = "K/KnitHttp" }
71d211c4-67af-4226-bf57-c04ce0a47fa7 = { name = "REPLBuilder", path = "R/REPLBuilder" }
7568ab37-29fa-429f-9993-a40ff907fe74 = { name = "KnitCore", path = "K/KnitCore" }
8880a6f3-ad0b-4cd1-b54c-bd72e2e73c43 = { name = "KnitConfig", path = "K/KnitConfig" }
a2bf8f19-0d18-4b4f-beab-d2df36dc25e4 = { name = "CompositeConfigLoader", path = "C/CompositeConfigLoader" }
ac4f51f7-48c2-4af3-adf1-f52a396a500e = { name = "KnitDI", path = "K/KnitDI" }
